jwt:
  secret:and0c2VjcmV0a2V5LXNwcmluZy1ib290LWp3dC1kYW1hLXNlY3JldC1qd3RzZWNyZXRrZXktZGFtYS1zcHJpbmdib290LXByb2plY3Q=

  access:
    expiration: 3600
    header: Authorization

    refresh:
      expiration: 3600
      header: Authorization-refresh